engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions:
          - php
      rulesets: "cleancode, codesize controversial, design, naming, unusedcode"
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"    
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/*
- Resources/*
- bin/*
- vendor/*
- var/*
