sudo: false
language: php
os:
  - linux
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
before_script:
  - ant
script: ant test
notifications:
  email: false
